name: pondai_app
description: "Pondai Housing Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  dio: ^5.7.0

  # Local storage / offline
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.3.4

  # State management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Secure token storage
  flutter_secure_storage: ^9.2.4

  # Connectivity detection
  connectivity_plus: ^6.1.4

  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  sqflite_common_ffi: ^2.4.0+3
  sqflite_common_ffi_web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true